config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :cars, except: [:destroy]
  # Defines the root path route ("/")
  # root "articles#index"
  root 'cars#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  validates :brand, presence: true
  has_many :variants

  accepts_nested_attributes_for :variants, reject_if: :all_blank, allow_destroy: true
end

app/models/variant.rb
class Variant < ApplicationRecord
  validates :name, presence: true
  belongs_to :car
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)

    if @car.save
      redirect_to @car
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])

    if @car.update(car_params)
      redirect_to @car
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def car_params
    params.require(:car).permit(:brand, :size, :rating, variants_attributes: %i[id name color _destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_car.html.erb
<h4>Main Information</h4>

<div>Brand: <%= car.brand %></div>
<div>Size: <%= car.size %></div>
<div>Rating: <%= car.rating %></div>

<h4>Variants</h4>
<% car.variants.each_with_index do |variant, i| %>
  <h5>Variant # <%= i + 1 %></h5>
  <div>Name: <%= variant.name %></div>
  <div>Color: <%= variant.color %></div>
<% end %>

app/views/cars/_form.html.erb
<% if car.errors.any? %>
  <div>Errors prevented this car from being saved:</div>
  <ul>
    <% car.errors
          .filter_map { |error| error.full_message if %i[brand size rating].include?(error.attribute) }
          .each do |message| %>
      <li><%= message %></li>
    <% end %>
    <% car.variants.each_with_index do |variant, i| %>
      <% if variant.errors.any? %>
        <li>
          <div>Variant #<%= i + 1%> Errors:</div>
          <ul>
            <% variant.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </li>
      <% end %>
    <% end %>
  </ul>
<% end %>

<%= form_with model: car do |form| %>
  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.text_field :size %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.text_field :rating %>
    <% car.errors.full_messages_for(:rating).each do |message| %>
      <%= message %>
    <% end %>
  </div>

  <div data-controller="variants-form"  
       data-variants-form-new-index-value="<%= car.variants.size %>">
    <h4>Variants:</h4>
    <div data-variants-form-target="container">
      <%= form.fields_for :variants do |variant_form| %>
        <div data-variants-form-target="fieldSet" data-index="<%= variant_form.index %>">
          <h5 data-variants-form-target="heading">Variant</h5>
          <div class="field">
            <%= variant_form.label :name %>
            <%= variant_form.text_field :name %>
          </div>
          <div class="field">
            <%= variant_form.label :color %>
            <%= variant_form.text_field :color %>
          </div>
          <div class="link"><%= link_to 'Delete This Variant', '#', data: { action: 'variants-form#deleteVariant' } %></div>
        </div>
      <% end %>
    </div>

    <div><%= link_to 'Add a variant', '#', data: { action: 'variants-form#addVariant' } %></div>
  </div>

  <%= form.submit %>
<% end %>

app/views/cars/edit.html.erb
<h2>Edit Car</h2>
<%= link_to 'Back to All Cars', cars_path %>

<%= render 'form', car: @car %>

app/views/cars/index.html.erb
<h2>All Cars</h2>
<h4><%= link_to 'New Car', new_car_path %></h4>

<% @cars.each_with_index do |car, i| %>
  <div><%= link_to "Car ##{i + 1}", car %></div>
<% end %>

app/views/cars/new.html.erb
<h2>New Car</h2>
<%= link_to 'Back to All Cars', cars_path %>

<%= render 'form', car: @car %>

app/views/cars/show.html.erb
<h2>View This Car</h2>
<div><%= link_to 'Back to All Cars', cars_path %></div>
<div><%= link_to 'Edit This Car', edit_car_path %></div>

<%= render @car %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StimulusCar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>